apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kukacz-podinfo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.1.6
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kcd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  values: |
    ingress:
      enabled: true
      hosts:
        - host: podinfo.kcd.sikademo.com
          paths: ["/"]
      tls:
        - hosts:
            - podinfo.kcd.sikademo.com
          secretName: podinfo-tls
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"

